version: '3.8'

services:
  mysql:
    image: mysql:8.0
    container_name: erp_mysql
    environment:
      MYSQL_ROOT_PASSWORD: local123
      MYSQL_DATABASE: erp_db
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
    networks:
      - erp_network

  backend:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: erp_backend
    ports:
      - "8080:8080"
    depends_on:
      - mysql
    environment:
      DB_HOST: mysql
      DB_PORT: 3306
      DB_USER: root
      DB_PASSWORD: local123
      DB_NAME: erp_db
    networks:
      - erp_network

volumes:
  mysql_data:

networks:
  erp_network:
    driver: bridge
